### PR TITLE
Py build

### PR DESCRIPTION
**Pull request by jeremybennett**
This is the first version of the Python build system. Documentation is currently somewhat limited.

It provides three commands:
* `build_all.py` to build all the benchmarks
* `benchmark_size.py` to yield the Embench code size statistics
* `benchmark_speed.py` to yield the Embench code speed statistics

This is still work in progress. Benchmarking speed in particular needs to be highly configurable to deal with all sorts of hardware and simulators. At present there is only one style of target set, which relies on a gdb being able to launch its own debug server to the target.

All commands have docstrings and `--help` works to list options. However I have yet to update the main documentation - that is the next job.

Here is how I run it using a gdbserver based on a Verilator model of the PULP RI5CY core:

To build everything:
```
  ./build_all.py --arch riscv32 --chip size-test-gcc --board ri5cyverilator --cc riscv32-unknown-elf-gcc
```
To get the size benchmark statistics:
```
  ./benchmark_size.py
```
To rebuild for speed optimization
```
  ./build_all.py --clean --arch riscv32 --chip speed-test --board ri5cyverilator --cc riscv32-unknown-elf-gcc
```
To get the speed benchmark
```
  ./benchmark_speed.py --absolute --target-module run-gdbserver-sim --gdb-command riscv32-unknown-elf-gdb --gdbserver-command riscv32-gdbserver --gdbserver-target ri5cy
```

### CODE REVIEW

**Comment by gmarkall** [comment]
I've just tried this - some notes / comments / questions:

1. Building and benchmarking for size works for me.
2. The size benchmarking script appears to output size relative to the reference platform, whereas existing documentation suggests that one needs to compute size relative to the reference platform - is a change to the documentation required to accompany the Python script for benchmarking size?
3. I haven't built the GDBServer for the reference platform - is there a list of directions for building it?
4. When I try to benchmark without having built the GDBServer, I get this error:

```
$ ./benchmark_speed.py --absolute --target-module run-gdbserver-sim --gdb-command riscv32-unknown-elf-gdb --gdbserver-command riscv32-gdbserver --gdbserver-target ri5cy
Benchmark           Speed
---------           -----
Traceback (most recent call last):
  File "./benchmark_speed.py", line 245, in <module>
    sys.exit(main())
  File "./benchmark_speed.py", line 227, in main
    raw_data, rel_data = collect_data(benchmarks, remnant)
  File "./benchmark_speed.py", line 180, in collect_data
    raw_data[bench] = benchmark_speed(bench, target_args)
  File "./benchmark_speed.py", line 137, in benchmark_speed
    res.stdout.decode('utf-8'), res.stderr.decode('utf-8')
  File "/data/graham/projects/everest/embench-iot/pylib/run-gdbserver-sim.py", line 97, in decode_results
    log.debug('Warning: Failed to find return code')
NameError: name 'log' is not defined
```

It's pretty clear (to me at least) what is wrong, but somehow `log` is not defined at this point (which is a bit strange).

**Comment by gmarkall** [comment]
Regarding 4 (the traceback), I had failed to spot the error was in run-gdbserver-sim.py. I think it just needs `log` importing:

```
diff --git a/pylib/run-gdbserver-sim.py b/pylib/run-gdbserver-sim.py
index ebcd03d..01ec883 100644
--- a/pylib/run-gdbserver-sim.py
+++ b/pylib/run-gdbserver-sim.py
@@ -16,6 +16,8 @@ Embench module to run benchmark programs.
 This version is suitable for a gdbserver with simulator.
 """

+from embench_core import log
+
 __all__ = [
     'get_target_args',
     'build_benchmark_cmd',
```

**Comment by jeremybennett** [comment]
Picking up on @gmarkall's comments:

> 1. Building and benchmarking for size works for me.

That's reassuring.

> 2. The size benchmarking script appears to output size relative to the reference platform, whereas existing documentation suggests that one needs to compute size relative to the reference platform - is a change to the documentation required to accompany the Python script for benchmarking size?

I believe the script is correct, and the documentation needs clarifying. I have yet to tackle the documentation.

> 3. I haven't built the GDBServer for the reference platform - is there a list of directions for building it?

Another one for the documentation. I used the `verilator-model` directory of the [standard RI5CY repo](https://github.com/pulp-platform/riscv), but because of bitrot, I found I had to use the older commit [300762a](https://github.com/pulp-platform/riscv/tree/300762ac295c57f409e05c6a9424d071dd4ebab5).  A simple call of
```
make
```
in the `verilator-model` will build the model in directory `obj_dir`.

I then built this into the [Embecosm RISC-V gdbserver](https://github.com/embecosm/riscv-gdbserver). This was configured with 
```
<riscv-gdbserver-dir>/configure \
    --with-verilator-headers=_<verilator-install-dir>_/share/verilator/include \
    --with-ri5cy-modeldir=<RI5CY-dir>/verilator-model/obj_dir --with-binutils-incdir= \
    --with-gdbsim-incdir= --prefix=<installdir>
```
(substituting directory names as appropriate)

> 4. When I try to benchmark without having built the GDBServer, I get this error:

_<snip>_

> It's pretty clear (to me at least) what is wrong, but somehow `log` is not defined at this point (which is a bit strange).

Fixed in commit [f50c5b5](https://github.com/embench/embench-iot/pull/9/commits/f50c5b5566682694fe6f6ac720ba7f745a22271d) as per your later comment.

**Comment by jeremybennett** [comment]
I believe the key questions raised have been addressed, so I am merging this pull request.

**Pull request merged**
