### PR TITLE
To resolve issue #84 

### PR DESCRIPTION
**Pull request by Roger-Shepherd**
Explain difference betweenPython module name (xyzzy) and its filename…(xyzzy.py)

### CODE REVIEW

**Comment by jeremybennett** [comment]
Hi Roger,

Thanks for the contribution. I think something went wrong with your patch. You've ended up with the use guide in the main `README.md` instead of `doc/README.md`. Could you check and resubmit.

Thanks.

**Comment by jeremybennett** [comment]
Hi Roger,

I can now see the change to `doc/README.md`. However all your changes to `README.md` are still there.

It might be simplest to start with a new pull request. Let me know if you want any help.

**Comment by Roger-Shepherd** [comment]
Jeremy 

A pointer to how to kill the current one and start a new would be welcome🙏 

Roger

Roger Shepherd
rog@rcjd.net

**Comment by Roger-Shepherd** [comment]
Closed and new one opened.

**Pull request closed without merging**
