### PR TITLE
arc: Update ARC gcc target

### PR DESCRIPTION
**Pull request by claziss**
Update ARC gcc target using an EM configuration compatible with RV32IMC.

xxxx-xx-xx  Claudiu Zissulescu  <claziss@gmail.com>

	* config/arc/arc-millicode.S: Delete.
	* config/arc/chips/em/chip.cfg: Update EM config.
	* support/dummy-libgcc.c: Add millicode dummy functions.

### CODE REVIEW

**Comment by jeremybennett** [comment]
@claziss 

Thanks for submitting the pull request. Looks great. I haven't had a chance to check it before merging. Do you have any results to share?

Best wishes,


Jeremy

**Comment by claziss** [comment]
@jeremybennett 
We use this configuration when comparing ARC EM with other compatible architectures. Please use it with the latest (mainline) gnu tools to get the current figures.

**Comment by PaoloS02** [comment]
Thank you very much for the contribution and sorry for the slow reply.
I wish to merge your changes soon.
May I ask you though to separate the changes to the different targets (ARC, ARM, RISC-V)  into different pull requests?

Meanwhile, about the configuration files: we are stirring towards the use of the benchmarks without relying on configuration files to store the compilation options. In the future the options should be passed only on the command line of the build script. This will allow more flexibility rather then having some of the options explicitly written in the master branch.
It's still work in progress, but we are working on a "results repo" where we can store the compilation options alongside with the results they produce.

Once the results repo is finalized it would be great if you could share the options you use and the results you obtain. That would be very helpful for any further contribution on the ARC target, but also to compare against the data we produced for ARM and RISC-V.

Many thanks,

Paolo

**Comment by claziss** [comment]
Hi,
I messed up that branch by rebasing. I'll make a new pull request with only ARC config. Thanks!

**Comment by PaoloS02** [comment]
Very appreciated, thank you!

**Pull request closed without merging**
