### PR TITLE
Benchmarking of Macs (2)

### PR DESCRIPTION
**Pull request by PaoloS02**
This pull request is the same as #127 only with a rearrangement of the history that allows a direct merge.
Some commits have been squashed and the message been merged.
Some empty spaces have been removed.
Some commits without effect (Linux support, moved to another branch) have been removed.
A commit that solves issue #126 has been put on another branch, ready to be merged once this pull request is merged as it isn't related to the current PR.

### CODE REVIEW

**Comment by PaoloS02** [comment]
@Roger-Shepherd hope you don't mind if I reworked a bit the history and cleaned a few things.
I carefully picked all the commits that weren't duplicating commits from master.
It would be of great help though if you could test that it still works as before, just to confirm.

**Comment by PaoloS02** [comment]
Once this is checked I'll merge this and the commit that solves issue #126 straight away.

**Comment by Roger-Shepherd** [comment]
Happy to have things cleaned up. I'm still learning how to work in this system. However, the fix to #126 will be needed, as the Mac is sensitive to this one - that's how I found it.

I'll check the other changes Friday a.m.


I'll check this works tomorrow. however
#126 is related to this PR. Mac won't work without #126 being fixed. (That's how I found the problem).

**Comment by PaoloS02** [comment]
Easily fixed. I added again the commit for the issue #126 on top.

**Comment by Roger-Shepherd** [comment]
You caught me out! I've just been looking and found that had been fixed!

**Comment by Roger-Shepherd** [comment]
It looks like I've a problem with trailing spaces in some of my files..... I though my editor stripped them, I'll have to check the reasons for that as I'm sure this can cause problems.

**Comment by Roger-Shepherd** [comment]
Checked on x86 Mac and ARM M1 Mac. Looks good to go.

**Comment by PaoloS02** [comment]
Good! I'll merge it then.

**Pull request merged**
