### PR TITLE
Add WebAssembly target configuration

### PR DESCRIPTION
**Pull request by I-mikan-I**
Added WebAssembly compilation target.

## Rationale

WebAssembly is a virtual instruction set finding use on embedded, low-resource devices due to its low-level semantics and tiny memory footprint.

Existing WebAssembly compatible benchmark suites target the browser execution environment and thus require browser bindings for execution
Compiling Embench to WebAssembly allows to compare the execution efficiency of different WebAssembly runtimes on SoC, without the presence of an operating system or browser.

### CODE REVIEW

**Comment by jeremybennett** [comment]
Hi @I-mikan-I 

Thanks for this substantial contribution. I will bring it up at today's monthly call, we we can get the code reviewed.

**Comment by wallento** [comment]
Thanks @jeremybennett, @I-mikan-I is the student I told you about. We are also working on running the embench tests on a variety of boards and runtimes.

**Comment by I-mikan-I** [comment]
Hi @jeremybennett 

Any update on the PR? :slightly_smiling_face:

**Comment by I-mikan-I** [comment]
Added WAMR configurations

**Comment by I-mikan-I** [comment]
Also closed due to embench 2.0

**Pull request closed without merging**
