### PR TITLE
Update benchmark_speed.py with new option to run benchmarks in p…

### PR DESCRIPTION
**Pull request by eosea**
…arallel for simulation.

### CODE REVIEW

**Comment by jeremybennett** [comment]
@eosea Nice work. I'm not a deep expert on Python, but it looks good to me.

One question. I think this will fire 19 threads, one for each benchmarks, each of which will start a compilation process. This is fine on a decent sized machine, but might overload a smaller machine (e.g. a laptop). Would it be easy to add an option to control the number of threads.

I've added @PaoloS02 as a reviewer - he runs Embench quite a lot, so would appreciate his input.

Would you be willing to talk about this at our call on Monday.

**Comment by jeremybennett** [comment]
I should have said, that after Monday's call I'll merge this if no one raises any issues. Thanks for your work on this.

**Comment by eosea** [comment]
It does launch one thread per benchmark.  I can add an option to specify a limit on the number of threads launched.  We can talk about this on the call this coming Monday.

**Comment by jeremybennett** [comment]
@eosea I have realized my comment was nonsense. Your patch is about _running_ the benchmarks in parallel, not building them. Since these are small benchmarks, I can't see that there would be a problem running them all at once even on a small machine.

**Comment by jeremybennett** [comment]
@eosea thanks for your contribution. This looks good to merge.

**Pull request merged**
